// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgrthktymsarxgcftaej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZncnRoa3R5bXNhcnhnY2Z0YWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNTgzMTYsImV4cCI6MjA3NzgzNDMxNn0.TBiMYgHLYMQr8TX50dxeN1CQ0TLDIF7PrDwnCkQeV3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});